version: "3"

services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: c.marc.aurele@outlook.com
      PGADMIN_DEFAULT_PASSWORD: cRgzyekS
    volumes:
      - "g_pgadmin:/var/lib/pgadmin"
      - "/tmp/servers.json:/servers.json"
    ports:
      - "5430:80"

volumes:
  g_pgadmin:

