# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$HOME/usr/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# added by Miniconda3 4.5.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/cmarc/applications/miniconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/cmarc/applications/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/cmarc/applications/miniconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/cmarc/applications/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<


# PROMPT
# CONDA_ENV_NAME=echo $CONDA_DEFAULT_ENV | rev | cut -d/ -f1 | rev
# export PS1=($CONDA_ENV_NAME)[\u@\h \W]\>