#!/bin/bash

qemu-system-x86_64 \
  -name "Fedora" \
  -machine type=q35,accel=kvm \
  -global ICH9-LPC.disable_s3=1 \
  -global ICH9-LPC.disable_s4=1 \
  -enable-kvm \
  -cpu host,kvm=off,hv_vapic,hv_relaxed,hv_spinlocks=0x1fff,hv_time,hv_vendor_id=12alphanum \
  -smp 6,sockets=1,cores=3,threads=2 \
  -m 8G \
  -mem-prealloc \
  -rtc clock=host,base=localtime \
  -device ich9-intel-hda -device hda-output \
  -device qxl,bus=pcie.0,addr=1c.4,id=video.2 \
  -vga qxl \
  -serial none \
  -parallel none \
  -k en-us \
  -usb \
  -device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1 \
  -boot menu=on \
  -boot order=b \
  -drive format=qcow2,file=./Fedora02.qcow2 \
  -device pci-bridge,addr=12.0,chassis_nr=2,id=head.2 \
  -device usb-tablet

  # -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd \
  # -device vfio-pci,host=01:00.0,bus=root.1,addr=00.0,x-pci-sub-device-id=0x087c,x-pci-sub-vendor-id=0x1028,multifunction=on,romfile=./vBIOS/nvidia/nvidia.rom \
  # -device ich9-intel-hda -device hda-output \

# The -device usb-tablet will not be accurate regarding the pointer in some cases, another option is to use
# -device virtio-keyboard-pci,bus=head.2,addr=03.0,display=video.2 \
# -device virtio-mouse-pci,bus=head.2,addr=04.0,display=video.2 \
