#!/bin/bash

qemu-system-x86_64 \
  -name "Windows10" \
  -machine type=q35,accel=kvm \
  -global ICH9-LPC.disable_s3=1 \
  -global ICH9-LPC.disable_s4=1 \
  -enable-kvm \
  -cpu host,kvm=off,hv_vapic,hv_relaxed,hv_spinlocks=0x1fff,hv_time,hv_vendor_id=12alphanum \
  -smp 6,sockets=1,cores=3,threads=2 \
  -m 8G \
  -mem-prealloc \
  -rtc clock=host,base=localtime \
  -device ich9-intel-hda -device hda-output \
  -vga qxl \
  -nographic \
  -serial none \
  -parallel none \
  -k en-us \
  -spice port=5901,addr=127.0.0.1,disable-ticketing \
  -usb \
  -device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1 \
  -device vfio-pci,host=01:00.0,bus=root.1,addr=00.0,x-pci-sub-device-id=0x087c,x-pci-sub-vendor-id=0x1028,multifunction=on,romfile=/home/cmarc/documents/vmdisks/nvidia.rom \
  -boot menu=on \
  -boot order=c \
  -drive format=qcow2,file=/home/cmarc/documents/vmdisks/windows10.qcow2 \
  -drive file=/home/cmarc/documents/vmdisks/virtio-win-0.1.141.iso,index=2,media=cdrom \
  -device pci-bridge,addr=12.0,chassis_nr=2,id=head.2 \
  -device usb-tablet
  
# The -device usb-tablet will not be accurate regarding the pointer in some cases, another option is to use 
# -device virtio-keyboard-pci,bus=head.2,addr=03.0,display=video.2 \
# -device virtio-mouse-pci,bus=head.2,addr=04.0,display=video.2 \