#!/bin/bash

# COLOR
NC=`tput sgr0`
RED=`tput setaf 1`

PWD=$(pwd)
ENV_NAME=`echo $(pwd) | rev | cut -d/ -f1 | rev`-env
ENV_FULL=$PWD/$ENV_NAME

echo " ⇨ You are in ${RED}$PWD${NC}"
echo " ⇨ The following env will be created : ${RED}$ENV_FULL${NC}"
read -p "Are you sure ?" -n 1 -r
echo    # (optional) move to a new line

if [[ $REPLY =~ ^[Yy]$ ]]
then
    conda create --prefix=$ENV_FULL python=3.7
    echo 
fi
